version: '3.8'

services:
  app:
    build: .
    expose:
      - "5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/medical_orders?schema=public
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=medical_orders
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  prisma-studio:
    build: .
    command: npx prisma studio --port 5555 --browser none
    expose:
      - "5555"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/medical_orders?schema=public
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
